import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SessionProvider } from "next-auth/react";
import { Session } from "next-auth";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Header } from "@/components/my-ui/header";
import SidebarUi from "@/components/my-ui/sidebar-ui";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Club Spacez",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  // pageProps: { session, ...pageProps },
  session,
}: Readonly<{
  children: React.ReactNode;
  // pageProps: any;
  session: Session;
}>) {
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={`${inter.className}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > 
            <SidebarProvider>
              <main className="w-full">
                
                <Header />
  
                <div className="flex md:m-7 gap-7">
                  <SidebarUi />
                  {children}
                </div>

              </main>
            </SidebarProvider>
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
